apiVersion: v2
name: security
description: A Helm chart for devtron to enable security integration
keywords:
  - kubernetes
  - security
  - k8s
  - scanning
  - container registry
  - image scanning
  - source code scanning
type: application
maintaintainers:
  - name: Pawan Kumar
    email: pawan.mehta@devtron.ai
sources:
  - https://github.com/Shivam-nagar23/charts
version: 0.1.5
appVersion: "0.1.1"
dependencies:
- name: clair
  version: "0.x.x"
  repository: https://shivam-nagar23.github.io/charts/
  condition: clair.enabled
